### ISSUE TITLE
about the train.ini

### ISSUE THREAD

**Issue by xiaowangfeng** [Xiaoxun-Gong/DeepH-E3#16]
Hello, I download the dataset in Zenodo. I find that Bilayer_graphene_train .ini in Zenodo is dffierent from train_default in default_configs. when i train the Bilayer_graphene_dataset,which one do I need to use?

**Comment by Xiaoxun-Gong** [comment]
Please use the `Bilayer_graphene_train.ini` in the Zenodo repository.
