### ISSUE TITLE
Issue with Training Two Structures

### ISSUE THREAD

**Issue by choi-geunseok** [Xiaoxun-Gong/DeepH-E3#5]
Hello, I am trying to train both HF and HfO2 simultaneously using the deeph-e3 code.
Have you ever trained such a case before?
When I tried, I found that while the eval matched well for HfO2, it was completely off for HF, which is why I am reaching out.
Thank you.

**Comment by Xiaoxun-Gong** [comment]
Hi, the current public version of DeepH-E3 does not support the case where the dataset is composed of structures with different chemical components. We are currently implementing this functionality and will release the revised version soon.

However, there is a way to avoid this problem: in you case, always let your graph data consist of both Hf and HfO2 in both training and evaluation. In other words: do not create a graph with only Hf structures. If you want to evaluate on Hf, then combine it with some HfO2 into the same graph.

**Comment by choi-geunseok** [comment]
Hi

In fact, as a stopgap measure, I already used both Hf and O when evaluating the HfO2 and Hf structures, placing HfO2 in the 0th position.

Thank you very much!
